version: 53
jobs:
- name: build
  jobExecutor: ghcr
  steps:
  - type: CheckoutStep
    name: checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - type: BuildImageStep
    name: build image
    output:
      type: RegistryOutput
      tags: ghcr.io/@project_path@:@build_number@
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: main
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  includeUpstreamWhenRebuild: false
  includeDownstreamWhenRebuild: false
  timeout: 14400
- name: pull remote
  steps:
  - type: CheckoutStep
    name: checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - type: PullRepository
    name: pull github
    remoteUrl: https://github.com/mistersupri/powerdrive.git
    userName: mistersupri
    passwordSecret: github
    targetProject: mistersupri/powerdrive
    accessTokenSecret: onedev
    refs: main
    withLfs: false
    force: true
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  includeUpstreamWhenRebuild: false
  includeDownstreamWhenRebuild: false
  timeout: 14400
